### ISSUE TITLE
zotxt not loading correctly

### ISSUE THREAD

**Issue by egh** [egh/zotxt#15]
When I run `org-zotxt-insert-reference-link` it calls something like `/zotxt/search?q=test&method=titleCreatorYear&format=quickBib`. Performing the same call by hand, `curl "http://127.0.0.1:23119/zotxt/search?q=test&method=titleCreatorYear&format=quickBib"`
results in

```
(5)(+0023984): GET /zotxt/search?q=test&method=titleCreatorYear&format=quickBib HTTP/1.1 Host: 127.0.0.1:23119 User-Agent: curl/7.64.1 Accept: */*

(5)(+0000002): HTTP/1.0 404 Not Found X-Zotero-Version: 5.0.82 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found 
```
And similarly, `curl "http://127.0.0.1:23119/zotxt/version"` results in 

```
(5)(+0337211): GET /zotxt/version HTTP/1.1 Host: 127.0.0.1:23119 User-Agent: curl/7.64.1 Accept: */*

(5)(+0000001): HTTP/1.0 404 Not Found X-Zotero-Version: 5.0.82 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain No endpoint found 
```

**Comment by egh** [comment]
Original issue https://github.com/egh/zotxt/issues/14

**Comment by egh** [comment]
I think I found the issue - see the new release https://github.com/egh/zotxt/releases/tag/v5.1.0

**Comment by Viehzeug** [comment]
Yes. It works with 5.1.0 for me now.

```
> curl "http://127.0.0.1:23119/zotxt/version"
{
  "version": "5.0.5"
}%
```

However, it seems the version end-point reports the wrong version. (But I'm glad it works)

**Comment by egh** [comment]
Whoops, I knew I shouldn't have hard-coded the version. Now I need to figure out how to get it from the metadata. Anyhow, glad the issue is fixed!

**Comment by egh** [comment]
@Viehzeug Actually, the issue should be fixed on zotero restart - you should see the new version then.

**Comment by Viehzeug** [comment]
Yes. It worked.
