### ISSUE TITLE
Can not install, plugin appears corrupt

### ISSUE THREAD

**Issue by dalanicolai** [egh/zotxt#16]
I can not install the add-on because on installing firefox shows the pop-up message: "This add-on could not be istalled because it appears to be corrupt"

I'm on linux (64-bit), Firefox 73.0

**Comment by egh** [comment]
@dalanicolai You need to install the plugin in zotero. If you are downloading on firefox, use right-click and then clock "Save link as"

**Comment by dalanicolai** [comment]
Ah wow, I clearly wasn't very awake when I read the instructions... thanks for your quick answer, it works perfectly now!

**Comment by egh** [comment]
Yeah, it's kind of confusing, I wish there were a better way :( Thanks for getting back to me!
