### ISSUE TITLE
Error when running pandoc-zotxt

### ISSUE THREAD

**Issue by sati-bodhi** [egh/zotxt#17]
I run into this error when invoking pandoc-zotxt.   

```
File "/usr/local/bin/pandoc-zotxt", line 5, in <module>
    from pandoczotxt import run
  File "/usr/local/lib/python3.7/site-packages/pandoczotxt/__init__.py", line 69
    except (urllib2.HTTPError, IndexError), e:
                                          ^
SyntaxError: invalid syntax
```

**Comment by egh** [comment]
Hi @sati-bodhi ! Thanks for the bug report. Is it possible to try to use https://github.com/odkr/pandoc-zotxt.lua instead? I am planning to deprecate pandoc-zotxt, as it is much more difficult to use than this other project, which is written in lua and runs natively in pandoc.

**Comment by sati-bodhi** [comment]
I was scared off by this [warning](https://github.com/odkr/pandoc-zotxt.lua#installing-pandoc-zotxtlua): 

![圖片](https://user-images.githubusercontent.com/7592695/75616453-fe1b3880-5b8b-11ea-8f3d-d8d0313a8ac7.png)

Will find the courage to give it a try, though. 👍

**Comment by egh** [comment]
It's better than python `pandoc-zotxt` in my opinion :)
