### ISSUE TITLE
Access group libraries

### ISSUE THREAD

**Issue by plantarum** [egh/zotxt#19]
Hello,

I'm trying to use zotxt via the org-zotxt package in Emacs. It appears to work for items in "My Library", which I can insert via `C-c " i`. However, it doesn't find anything in my group libraries. I'm not sure if this is an issue with zotxt, org-zotxt, or zotxt.el, or me. Is it possible to retrieve items from Group Libraries via zotxt, and if so, what should I be doing to enable this?

Thanks,

Tyler

**Comment by egh** [comment]
Thanks for the report @plantarum It's been a while since I dealt with group libraries, sorry. Querying zotxt seems to work for group libraries if you include the `library=all` parameter, but this isn't supported in zotxt-emacs.

This is easy enough to add, but I'm not sure what the interface should be. I am thinking perhaps a variable that by default is set to `"all"` to search all libraries. There could also be a setting for `'user` or something to only search your own library, and `'prompt` to ask for which library to search. What do you think would be most useful?

**Comment by plantarum** [comment]
Hi @egh!

I am new to Zotero, and exploring using it to replace my .bib database. I actually quite like org-ref support for bibtex, but Zotero makes it much easier to share with colleagues, so I'm moving in that direction.

As for the interface, I think having customization option for groups, with the default being 'all', would make sense. Then provide a prompt to select groups interactively should the user call the command with a prefix (`C-u`)? Or are you already using the prefix for something else?

In other contexts, I use packages that provide a separate command when you want to switch an option. With that approach, you wouldn't use the prefix option, but would instead provide a command like `zotxt-set-group` that you call explicitly to do that. That would be ok too.

Thanks for sharing this!

**Comment by egh** [comment]
Yes, I think `org-ref` is a better system than zotxt :) But I like Zotero and I don't really use bibtex, so I have this. I'm curious to hear your thoughts!

The prefix is used for something else, but I think we could double up the usage. Thanks for the feedback! I should have a commit to default to searching by all libraries tonight.

**Comment by egh** [comment]
I've pushed a fix for this that should be available on MELPA soon.

**Comment by plantarum** [comment]
Great, thanks!

I've forked it and will install locally, so I can tweak it if 
needed, and will push anything useful back to you. Assuming I can 
figure it out. I'm quite comfortable with elisp, but don't know 
Ruby or the Zoteroa API.

Best,

Tyler

Erik Hetzner writes:

> I've pushed a fix for this that should be available on MELPA 
> soon.


-- 
Tyler Smith
plantarum.ca

**Comment by plantarum** [comment]
Works as advertised!
