### ISSUE TITLE
Installation Documentation for Windows

### ISSUE THREAD

**Issue by jsbangsund** [egh/zotxt#2]
Is zotxt compatible with windows? I'm running the most recent version of Zim Wiki, but there is no "Add-ons" option in the Tools Menu.

"Custom Tools" seems like it might be close, but there is no install from file option, just commands that can be pasted in.

Thanks for any advice you can provide.

**Comment by egh** [comment]
It should be compatibile, as far as I know. Are you using Zotero standalone? I'm not sure what zim wiki is.

**Comment by jsbangsund** [comment]
I was being blind somehow and just missed the menu options. The installation documentation is fine.

Sorry about that.

**Comment by egh** [comment]
Great! I'm glad you got it installed.
