### ISSUE TITLE
Zotxt incompatible with Zotero-fork Juris-M

### ISSUE THREAD

**Issue by zenny** [egh/zotxt#24]
Hi,

zotxt-5.1.0 cannot be installed into Juris-M which is a fork of Zotero (https://juris-m.github.io/), says:

`The add-on "zotxt" could not be installed. It may be incompatible with this version of Jurism.`

Thanks!

**Comment by egh** [comment]
Thanks for the report! I believe this should be fixed in the latest release: https://github.com/egh/zotxt/releases/tag/v5.1.1

**Comment by zenny** [comment]
@egh Thanks!
