### ISSUE TITLE
Feature request: locale parameter

### ISSUE THREAD

**Issue by chrmoe** [egh/zotxt#26]
Could you add a "locale" or "lang" parameter that we could use to ask Zotero for bibliographies formatted for specific locales?

Different locales use different punctuation and different localized strings for "editor", "and", "in", etc. 

Switching default locale manually in the Zotero app is possible but cumbersome (needs restarting). Too cumbersome for my use case (generating a multi-language static web site with references in multiple documents).

Back in the days of zotero-plain I tweaked zotero-generate-bib-entry to do this by replacing the "bibliography=" string in the second parameter in the call to Zotero.QuickCopy.getContentFromItems with a contentformat object that included a "locale" property containing a language code like "fr". I seem to remember that I had it working smoothly. Perhaps something like that could be done for zotxt.

**Comment by egh** [comment]
Oh, sure! In fact this looks pretty easy. I'm sorry I missed it before.

**Comment by egh** [comment]
https://github.com/egh/zotxt/pull/27 I think this would fit your needs?

**Comment by chrmoe** [comment]
Thanks for the fast response! Looks great. I'll try to build and test it when I get off work tonight.

**Comment by chrmoe** [comment]
Working like a charm! Thank you.

**Comment by egh** [comment]
Great! Thank you for testing.
