### ISSUE TITLE
Zotxt (v6.0.2) settings disappeared from inside Zotero (v6.0.26) preferences. 

### ISSUE THREAD

**Issue by ffsammak** [egh/zotxt#38]
Hi, I used to have Zotero working in sync with Emacs using zotxt until, I guess 1. Aug, when some update happened on Zotero end. My Zotero version is 6.0.26, I ran into issues with BBT renaming, so I had to update BetterBibTeX plugin to 6.7.101 and ZotFile to v5.1.3 (development version). I noticed that Emacs is not picking up newly added references, and I can no longer see the settings related to zotxt plugin (currently v6.0.2) inside Zotero preferences. Am I missing something? Your help is greatly appreciated.

**Comment by egh** [comment]
How do you use sync?

**Comment by ffsammak** [comment]
Oh, sorry my bad. The sync is via BBT not zotxt. Apologies.
