### ISSUE TITLE
zotxt 6.0.2 – won’t find items with non-ASCII citation keys

### ISSUE THREAD

**Issue by odkr** [egh/zotxt#39]
I just tried to insert a citation to a paper by Esa Díaz-León, using the Better BibTeX Citation key "Díaz-LeónWhat2015". However, zotxt responds: "Díaz-LeónWhat2015 had no results". I tried changing the citation key to "Diaz-LeonWhat2015", but that just gives the same error. I can reproduce that behaviour with other citation keys that contain non-ASCII characters.

I conjecture that zotxt uses the citation key to search for the author, so forcing an ASCII citation key doesn’t help, because the author name is not saved in ASCII. My best guess for why the UTF-encoded citation key is not found are unicode normalisation issues. It may be that my editor enforces a different normal form than Zotero. I’m not sure how to best address this, since applications have some leeway when it comes to normal forms. But if my guess is right, it’s probably best to normalise incoming strings to NFC, since that is what web sites should use; it's also the most common one.

I’ll investigate further when I have more time.

Thanks for looking into this!

**Comment by odkr** [comment]
I did have a closer look at the behaviour. And it appears I was wrong, the bug does not appear to be related to Unicode normalisation.

This is the citation key as Zotero copies it to the clipboard:

```sh
% pbpaste > foo.md
% sed 's/^@//' foo.md
Díaz-LeónWhat2015%
% sed 's/^@//' foo.md | hexdump
0000000 c344 61ad 2d7a 654c b3c3 576e 6168 3274
0000010 3130 0035
0000013
```

This is what happens when I run it through Pandoc:
```sh
% pandoc -L pandoc-zotxt.lua -C foo.md
pandoc-zotxt.lua: zotxt responded: "Díaz-LeónWhat2015 had no results"
[WARNING] Citeproc: citation Díaz-LeónWhat2015 not found
<p><span class="citation"
data-cites="Díaz-LeónWhat2015">(<strong>Díaz-LeónWhat2015?</strong>)</span></p>
% pandoc -L pandoc-zotxt.lua -C foo.md 2>&1 | sed -n 's/.*"\(.*\) had.*/\1/p'
Díaz-LeónWhat2015
% pandoc -L pandoc-zotxt.lua -C foo.md 2>&1 | sed -n 's/.*"\(.*\) had.*/\1/p' | hexdump
0000000 c344 61ad 2d7a 654c b3c3 576e 6168 3274
0000010 3130 0a35
0000014
```

Indeed, the key appears to be normalised to NFC already:
```
% sed 's/^@//' foo.md | uconv -f utf-8 -x nfc | hexdump
0000000 c344 61ad 2d7a 654c b3c3 576e 6168 3274
0000010 3130 0035
0000013
```

That said, I don’t see how non-ASCII characters not being matched could be caused by something other than encoding issues. I haven't checked whether Zotero or Pandoc normalise their input. But if they do, I would be surprised if they normalised it to anything other than NFC.

I am using Pandoc 3.1.8 with Zotero 6.0.29 on macOS 14.0.

**Comment by odkr** [comment]
Okay, I could find out more. Did you change how Better BibTeX keys work? Should I have been paying more attention to the release notes?

Because:
```sh
# No response
% curl 'http://localhost:23119/zotxt/items?betterbibtexkey=BergerSocial1967'
% curl 'http://localhost:23119/zotxt/items?easykey=BergerSocial1967'
[
  {"id":"BergerSocial1967","author":[{"family":"Berger","given":"Peter L."},{"family":"Luckmann","given":"Thomas"}],"citation-key":"BergerSocial1967","event-place":"London","issued":{"date-parts":[[1967]]},"publisher":"Penguin","publisher-place":"London","title":"The social construction of reality: a treatise in the sociology of knowledge","title-short":"The Social Construction of Reality","type":"book"}
]
```
I didn't notice because pandoc-zotxt.lua cycles through citation key types until it gets a match.

However:
```sh
% curl 'http://localhost:23119/zotxt/items?easykey=Díaz-LeónWhat2015'
"DÃaz-LeÃ³nWhat2015 must be of the form DoeTitle2000 or doe:2000title"%
% curl 'http://localhost:23119/zotxt/items?easykey=Díaz-León:2015What'
"DÃaz-LeÃ³n:2015What must be of the form DoeTitle2000 or doe:2000title"%
% curl 'http://localhost:23119/zotxt/items?easykey=HäggqvistKinds2005'
"HÃ¤ggqvistKinds2005 must be of the form DoeTitle2000 or doe:2000title"%
% curl 'http://localhost:23119/zotxt/items?citekey=HäggqvistKinds2005'
```

It would seem that whatever test you used to check whether a citationkey matches DoeTitle2000 or doe:2000title uses an encoding other than UTF-8 on my system.

**Comment by odkr** [comment]
It would seem that this is fixed in version 0.3 🙂. Thank you!

**Comment by egh** [comment]
Not sure exactly what fixed this, but I'm glad it works!

**Comment by odkr** [comment]
Oh, I just realised, it was never zotxt to begin with! It was Pandoc. And me 🤦.

The request URL wasn't properly escaped:

```bash
$ curl 'localhost:23119/zotxt/items?easykey=Díaz-LeónWhat2015'
"DÃaz-LeÃ³nWhat2015 must be of the form DoeTitle2000 or doe:2000title"
$ curl 'http://localhost:23119/zotxt/items?easykey=D%C3%ADaz-Le%C3%B3nWhat2015'
[
  {"id":"Díaz-LeónWhat2015","accessed":{"date-parts":[["2015",11,14]]},"author":[{"family":"Díaz-León","given":"Esa"}],"citation-key":"Díaz-LeónWhat2015","container-title":"European Journal of Philosophy","container-title-short":"Eur J Philos","DOI":"10/gh868s","ISSN":"1468-0378","issue":"4","issued":{"date-parts":[["2015"]]},"language":"en","license":"© 2013 John Wiley & Sons Ltd","original-date":{"date-parts":[["2013"]]},"page":"1137-1152","source":"Wiley Online Library","title":"What Is Social Construction?","type":"article-journal","URL":"http://onlinelibrary.wiley.com/doi/10.1111/ejop.12033/abstract","volume":"23"}
]
```

Apparently they fixed that in one of their recent releases.
