### ISSUE TITLE
Zotxt is incompatible with Zotero 7.0.3

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [egh/zotxt#45]
That's what my freshly updated Zotero "extensions" dialog box says.

A cursory look at #37 led me to hope this was solved.

What can we do to help ?

**Comment by egh** [comment]
Hi @EmmanuelCharpentier ! Thanks for the reminder. I hadn't finished updating the release. I *think* it should auto-update, but so much has changed since Zotero 6. If it doesn't auto-update, it's available here: https://github.com/egh/zotxt/releases/tag/v7.0.0

**Comment by EmmanuelCharpentier** [comment]
Zotxt didn't auto-upgrade (neither pn Windows nor on Linux). Manually removing it and reinstalling a manually downloaded version seems to have worked.

More on this after tests (but I have some NMIs to process first...).

**Comment by egh** [comment]
Great, thank you!
