### ISSUE TITLE
zotext no longer supported on recent versions

### ISSUE THREAD

**Issue by Cloud0Envy** [egh/zotxt#7]
Hi,
The latest version of zotero (version 4.0.29.10) does not support this extension. Any updates or possibility of compatibility?

Regards
Cloud

**Comment by egh** [comment]
@Cloud0Envy The latest version of Zotero is 5.0.58. Zotero 4 is no longer supported. Sorry!

**Comment by egh** [comment]
@Cloud0Envy The latest version of Zotero is 5.0.58. Zotero 4 is no longer supported. Sorry!

**Comment by Cloud0Envy** [comment]
Hi,
Needed a clarification. I'm using [Juris-M](https://juris-m.github.io/) (5.0.52m40). This should be Zotero 5? I understand I should contact Juris-M developers preferably. 
Apologies for citing the Zotero Standalone version which I don't use.
